# Setup
title:               Laura Cashman
tagline:             'Quantitative Social Scientist'
sidebar_text:        'Please <a href="/contact" title="Contact">reach out</a> if you ever feel the desire to do so!'
url:                 https://lauracashman.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Laura Cashman
  twitter-username:  lauranichiosain
  github-username:   lauracashman
#  url:               
# email:

# Gems
theme: jekyll-theme-lanyon
plugins:
  - jekyll-paginate

# Custom variables
version:             1.1.0
